---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Notas sobre Linux 

<!-- badges: start -->
<!-- badges: end -->

Este repositorio es un compendio de notas que he tomado sobre Linux. Está en 
construcción y suponen apuntes que he ido tomando de cursos, libros y experiencias
en mi día a día trabajando en ciencia de datos con sistemas operativos Linux.

Siéntase libre de tomar las notas, probar lo que hay, modificarlo y mejorarlo.
Prácticamente todo lo que está escrito ha sido tomado de otros tutoriales, guías,
libros y documentación de personas que comparten algo de su conocimiento. Así 
que, bajo la premisa de todos aprendemos de todos, espero que logren aprender
algo de lo que aquí he anotado.

## ¿Cómo están organizadas las notas?

De momento hay mucha entropía. Es un trabajo en construcción así que cuando
tenga listo una especie de índice lo estaré colocando acá.

## Aspectos técnicos de las notas

Todas las notas las he ido tomando en archivos `.Rmd` [Rmarkdown](https://bookdown.org/yihui/rmarkdown/)
Es un formato bastante útil que me ha permitido combinar texto con el lenguaje
de programación R y pequeños scripts de bash.

El resultado de los archivos `.Rmd` que acá encontrará es un `HTML`. 

## Mejoras

Si en algún punto de las notas encuentran mejores explicaciones o bien errores,
por favor dejen un issue (tiquete) o mejor aún, un pull request (solicitud de
fusión)
